version: '3.9'

services:
  server:
    build: .
    ports:
      - 3000:3000
    depends_on:
    - "db"
    links:
    - db
    secrets:
    - my_secret
  db:
    image: 'postgres'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      APP_DB_NAME: 'prod'
secrets:
  my_secret:
    file: ./.env